# Synthesis 

Apex predators can suppress mesopredators and prey through two nonexclusive pathways: density and behavioural mediation [@ripple2016trophic]. 

In this thesis, I inferred that foxes mediated the density of cats in Chapter \@ref(density). I observed a numerical increase in cats following fox control, and negative associations between fox occurrence probability and cat density at fine spatial scales. More cats in a system following fox control will lead to higher consumption of their prey, although this relationship may not be linear [@abrams1993predation; @moseby2015catastrophic] and needs to be weighed against the benefits of having fewer foxes in the system. 

Behavioural mediation between an apex and a mesopredator is more difficult to quantify and predict than density mediation [@ford2015trophic]. I found that fox activity likely lowered cat detectability (Chapter \@ref(occ); Chapter \@ref(density)) and shifted their diel patterns (Chapter \@ref(diel)), potentially reflecting fox avoidance behaviours. A relaxation of cat behaviour following fox control is likely to increase cat hunting success, and/or shift their impacts onto different prey species. However, these patterns were less consistent across my study regions relative to changes in cat density. 

In this synthesis, I will examine the evidence for fox control causing a mesopredator release of cats, in terms of both density and behavioural mediation. I will also discuss the potential implications for native prey and hence invasive predator management for conservation, as well as highlight future research priorities throughout. 


## Density mediation
The classic definition of the mesopredator release hypothesis (hereafter ‘MRH’) is that a decline in the population of an apex predator causes an increase in the density of mesopredators [@soule1988reconstructed]. Yet, few studies have tested or demonstrated this, partly due to the difficulty of robustly estimating predator density. By using spatially explicit capture-recapture methods which allowed for flexible detection rates, I was able to provide the first evidence that fox control can increase the density of cats (Chapter \@ref(density)). 

The impact of fox control on cat density&mdash;ranging from no effect to a nearly four-fold increase in cat density&mdash;appeared dependent on the degree of fox suppression (Chapter \@ref(density)). This was further evidenced by a negative relationship between cat density and fox occupancy estimates at fine spatial scales (Fig. \@ref(fig:dcor)). The strongest effects came from the Glenelg region (Chapter \@ref(density)). Fox control in the Glenelg region has occurred for more than a decade and has substantially reduced fox occupancy rates (Chapter \@ref(occ)). Cat density increased with fox control to a smaller extent in the Otway Ranges, which was unsurprising given that (a) fox occurrence in my study area was already low prior to lethal control, (b) fox control only recently commenced, and (c) fox-baits were replaced less frequently than in Glenelg. These results highlight the importance of measuring apex predator activity alongside mesopredator density when testing the MRH, rather than simply relying on binary treatments of apex predator decline [@brook2012effects; @salo2010predator]. 

It is hypothesised that apex predators may only place an upper limit on mesopredator density [@johnson2009evidence; @letnic2011does]. In the Otway Ranges—but not the Glenelg region—the non-linear model supported this hypothesis: cat density was only estimated to decline in the mid-high range of fox occurrence probabilities, while remaining steady at low fox occurrence probabilities (Fig. \@ref(fig:dcor)). Further, the nonlinear relationships between fox occurrence probability and cats in the Otway Ranges (Fig. \@ref(fig:detcor); Fig. \@ref(fig:dcor)) suggested that a relaxation of cat antipredator behaviours may cause a lagged increase in cat density (Chapter \@ref(density)). While speculative, my study is one of the first to be able to test this given my models (a) separated population density from behavioural processes and (b) allowed nonlinear responses. 


## Behavioural mediation
Recently, the definition of the MRH has been expanded to also capture changes in mesopredator distribution and behaviour following apex predator decline [@brashares2010ecological]. In my thesis, I explored these angles using occurrence models (Chapter \@ref(occ)), spatial detection rates in cat density models (Chapter \@ref(density)), as well as spatiotemporal activity (Chapter \@ref(diel)) models. In contrast to the changes in cat density described above, changes in cat behaviour in response to fox activity were relatively inconsistent across replicates and regions. The relationship between the probability of fox occurrence on cat detectability varied between regions. In the Glenelg region, there was little evidence that cat spatial detection rates changed with fox control or across fox occurrence probability gradients (Chapter \@ref(density)). In the wet forests of the Otway Ranges, spatial capture-recapture models revealed that cats did not range as far and were more detectable in their activity centre when fox occurrence was low (Fig. \@ref(fig:detcor)), suggesting behavioural avoidance. This was supported by occupancy-detection model, which estimated cats to be slightly more detectable with fox control across the Otway Ranges (Fig. \@ref(fig:occ-det)a). 

Landscape context and the level of perceived risk mediate antipredator strategies [@wirsing2021context]. A key result of my study is identification of differences in fox and cat ecology between wet and dry vegetation types. Fox occupancy was lowest and cat occurrence was highest in the wet forests relative to dry vegetation types (cat densities were also very high in the wet forests; Chapter \@ref(otways17)).  Similarly, there were substantial differences in behaviour. Foxes were mostly nocturnal in dry vegetation types but had little variation in activity throughout the daily cycle in wet forests. Cats on the other hand were mostly crepuscular in dry vegetation types, and nocturnal in wet forests. Differences in potential antipredator strategies were further highlighted in Chapter \@ref(diel), which suggested cats avoid foxes temporally by becoming more diurnal in dry vegetation types but by reducing activity around dawn in wet forests (Fig. \@ref(fig:diel-cat-fox)). I suspect these difference in antipredator strategies relate to differences in prey species (e.g., diurnal reptiles are scarce in wet forests) and shelter availability (cats likely have more opportunity to escape following a fox encounter in the more structurally complex wet forests), as well as fox encounter rates (lower occurrence probabilities in wet forests) between these habitat types. We have long been aware of the role of predator behavioural mediation in ecosystem function [@schmitz1997behaviorally], but still have a somewhat poor ability to predict behavioural changes following apex predator decline [@prugh2019designing; @peacor2013costs]. Testing antipredator responses in mesopredators across a wider range of landscape contexts will be key to further establishing general patterns of behavioural mediation. 

There are several other potential ways cats could have altered behaviour following fox control which my thesis did not investigate, such as diet and fine-scale habitat preferences. For example, coupling telemetry and diet analyses, @molsher1999ecology found cats increased their use of more open habitat types and consumed more carrion and invertebrates following fox control [@molsher2017mesopredator]. However, following fox eradication on Phillip Island, @rendall2022does found no evidence of prey switching, although cats slightly increased their consumption of invertebrates and black rats *Rattus rattus*. In another forested region of Victoria, @buckmaster2012ecology hypothesised that large 'holes' in the home range of each GPS-collared cat could be due to apex predator avoidance; in contrast @roshier2021space found no strong evidence that cat distributions were influenced by foxes in an arid region. There is currently no information on cat diet or habitat selection from south-west Victoria, making this a priority for future research to provide a better understanding of both mesopredator release and how cat ecology differs between Australian regions. 


## Strength of evidence about mesopredator release
While my study provides evidence consistent with the MRH, it had several limitations. In the Glenelg region, I cannot be sure that feral cat density or occupancy did not differ between impact than non-impact landscapes prior to fox control commencing (because there is no available data). However, the spatial replication of the control-impact experimental design (three paired impact and non-impact landscapes) increases confidence in the accuracy of my results. I was able to overcome this limitation in the western Otway Ranges by using a Before-After-Control-Impact-Paired-Series (BACIPS) design. However, effects of fox control were weaker in the Otway Ranges relative to the Glenelg region and there was some overlapping of confidence intervals, indicating weak statistical evidence for mesopredator release. Further, I was unable to replicate the BACIPS design in the Otway Ranges, increasing the vulnerability to type I error [i.e., falsely inferring there was an effect of fox control on cats, @conquest2000analysis]. These issues are common limitations with predator management experiments [@ford2015trophic] but can still provide robust, clear evidence when ultimately combined in meta-analyses.

A key source of contention around the MRH is the use of associative rather than causal inference [e.g., @allen2013clear; @hayward2015ecologists]. Replicated experimental treatments (e.g., fox control and no fox control) are often considered the ‘gold standard’ in experimental designs. However, experimental treatments are often imperfect in large scale ecological field experiments because treatment effectiveness varies [among several other reasons, @kimmel2021causal; @ford2015trophic]. An increasingly valued alternative to replicated experiment treatments is testing responses across experimental gradients [@ford2015trophic]. Testing responses across experimental gradients (e.g., fox occurrence when subject to lethal control) strengthens inference relative to ‘natural’ observation data and is more feasible to implement relative to replicated large-scale predator treatments [@ford2015trophic]. Experimental gradients are particularly important when responses are nonlinear [@kreyling2018replicate], as intraguild predator interactions are often thought to be [e.g., @letnic2011does]. 

My thesis is unique in that I combined traditional experimental treatment designs and experimental gradients (with both linear and nonlinear regression methods) to test the MRH with the same datasets. Both approaches provided causal inference because foxes were artificially manipulated, and fox control was not knowingly confounded with other variables (except latitude in the Glenelg region - all treatment landscapes were slightly south of the non-treatment landscapes). The addition of experimental gradients was particularly useful in the Otway Ranges where fox control effort was inconsistent; simplifying fox control into a binary treatment variable overlooked important nuance such as bait density and replacement schedules. Quantifying fox activity along gradients expressly measured the likelihood of cats encountering foxes and so provided a more accurate reflection of intraguild predator interactions. Traditional experimental designs are often called for in testing the MRH [e.g., @glen2007evaluating; @hayward2015ecologists], but a range of experimental approaches can provide complementary and robust causative inference on management interventions [@ford2015trophic].

Given the consistency and long-term nature of fox control in the Glenelg region, it is likely that predator-predator and predator-prey interactions have stabilised since fox control commenced (i.e., the effect of fox control has had a chance to distil and be detected). This is unlikely to be the case in the Otway Ranges, given we only monitored for 1.5 years following the commencement of fox control and during this time, the control effort was inconsistent. This makes it difficult to draw long-term conclusions around species interactions in the Otways from our observations [@yodzis1988indeterminacy]. I recommend these surveys be repeated in the longer term to provide a better understanding of the impact of fox control. Longer-term surveys in the western Otway Ranges would be provide rich information on fox-cat-prey interactions given the relative absence of other disturbances compared to other regions in Australia which likely have more transient dynamics [e.g., @greenville2014bottom]. 

Two major constraints to the widespread use of spatial capture-recapture surveys to monitor cat populations are (i) the long and arduous process of individual cat identification and (ii) obtaining sufficient statistical power to detect population changes in a before-after-control-impact design [@efford2019fast]. To address one of the most time-consuming parts of the survey process, collaborators and I have been trialling machine learning methods to automatically identify species and individual cats from camera-trap images; these show promise and are likely to increase the feasibility of such studies by management agencies [@yang2021individual]. Nonetheless, reliable estimates from spatial mark-resight models require large sample sizes, which were difficult to obtain, despite extensive and intensive survey effort (41,216 trap nights) and the Otway study region having one of the highest density populations of cats on the Australian mainland (Chapter \@ref(otways17)). For regions with lower densities of cats, sufficient sample sizes may be more feasibly achieved using clustered spacing of camera-traps over larger areas rather than the grid designs we used [@clark2019comparing; @sun2014trap]. A key benefit of spatial capture-recapture studies is that differences in study designs can be accounted for analytically, allowing feral cat density estimates to be collated across different landscapes, regions and fox control programs. This will be particularly important to identify how different management regimes and landscape contexts impact the strength and occurrence of mesopredator release. 


## Direct or indirect suppression?
Mesopredator release following the decline of an apex predator population can occur directly due to a decrease in aggressive encounters experienced by the mesopredator, or indirectly through increased availability of shared prey [@prugh2009rise]. These pathways are difficult to tease apart in my study system, given I studied similar sized predator species in a depauperate predator guild, and so both direct and indirect effects are expected to be strong [@brashares2010ecological; @prugh2020enemies; @donadio2006diet]. The negative correlations between fine-scale cat density and fox occurrence I observed (Chapter \@ref(density)) supports a direct top-down suppressive effects of foxes on cats. Ascertaining the contribution of indirect prey effects in mesopredator release would require a negative association between foxes and prey, but it is unclear whether a positive or negative association with cats and prey signal competitor release: a positive association could infer cats are tracking the prey or alternatively, be interpreted as peaceful coexistence.

Prey abundance often increases dramatically several years after fox control [@duncan2020eruptive], which could explain why cat activity also tends to increase [@hunter2018not], and prey populations often subsequently crash [@duncan2020eruptive]. @duncan2020eruptive hypothesised that these trends were due to prey overshooting carrying capacity following the release from top-down suppression by foxes; however, our study offers an additional explanation by demonstrating that cat density steadily increases following the commencement of fox control (Otway Ranges) and may remain relatively high in the long-term (Glenelg region). There is currently very little information on how prey availability impacts cat density, particularly in temperate regions [@legge2017enumerating], which makes it difficult to understand the relative importance of direct and indirect mesopredator release effects. Nonetheless, this information may not actually be relevant to decision-making around predator management&mdash;if fox control increases cat impacts on native prey, does it matter what mechanisms are responsible?
 

## Piecing together mesopredator release 
My thesis provides evidence that fox control frees cats from top-down constraints on population density and diel activity patterns in temperate forests, meeting the definitions of mesopredator release [@jachowski2020identifying; @prugh2009rise; @brashares2010ecological]. A key strength of my thesis is that I investigated interactions between these two species in simplified predator guilds, and from several different angles, with replication across two distinct study regions. 

Cats are ubiquitous across Australia [@legge2017enumerating] and my study regions. My study concurs with numerous others which have shown little-no evidence that apex predators restrict the spatial distribution of cats [e.g., @edwards2002habitat; @brook2012effects; @wang2012dingoes; @fancourt2019introduced; @stobo2020habitat; @roshier2021space;]; however, I found that cats changed their behaviour and had lower population densities where foxes were common. Spatial co-occurrence between predator species is increasingly used to test the MRH [@jachowski2020identifying], but can be a poor proxy for species interactions [@guillaume2020co] and overlook other antipredator behaviours, such as reactive spatial avoidance [@broekhuis2013risk], and temporal avoidance  [@kronfeld2003partitioning]. The use of different analytical methods and population metrics helped identify that mesopredator release manifests in different ways, which may have important consequences for biodiversity conservation (discussed in the section below). 

While there are several limitations of this study, I believe it provides an important case study for the MRH. High-profile examples of mesopredator release are largely based on the complete extirpation of apex predators&mdash;rather than population suppression&mdash;often without replication [e.g., @rayner2007spatial]. This has led to uncertainty around the generalisability of mesopredator release and whether lethal predator control programs are sufficient to trigger mesopredator release [@ford2015trophic]. My study increases confidence that mesopredator release can occur predictably across different regions (at least in terms of population density), although the strength of the effects depends on the degree of apex predator suppression.


## Implications of mesopredator release for native prey 

The primary aim of this thesis was to understand whether mesopredator release was occurring rather than its implications for native fauna. Nonetheless, I found that long-nosed potoroos strongly benefit from fox control in terms of site occurrence in the Glenelg region regardless of any mesopredator release of cats (but not the Otway Ranges). In contrast, southern brown bandicoots showed no response to fox control in terms of occurrence, potentially because they are more susceptible to cat predation.   

It is likely that fox control will benefit some native prey, but not others. There is high dietary overlap between foxes and cats; however some native prey, particularly larger species, are more susceptible to foxes than cats [@stobo2021reptiles; @stobo2021sharing; @woinarski2021compounding]. For example, a density of 0.03 foxes km^-2^ drove a reintroduced population of burrowing bettongs *Bettongia lesueur* to extinction within 12 months in the absence of cats, but another population persisted with no foxes and up to 0.46 cats km^-2^ [@moseby2019understanding]. While there is currently no statistical evidence that the size of native prey affects their response to fox control [@hunter2018not], the prey species expected to benefit the most from fox control, in particular macropods, are often the focus of associated monitoring programs. More work is needed to examine the responses of different prey species to fox control, particularly smaller species (e.g. rodents and small dasyurids), which are more sensitive to cat predation.

If fox control increases the density of feral cats, it is likely that the impact of feral cats on native fauna will increase. However, it is important to note that predation rates of particular species may not necessarily increase linearly with cat population density. Predation rates depends on cat demographics [@moseby2015catastrophic], individual specialisation [@dickman2015individual], as well as predator and prey behaviour [@abrams1993predation] and microhabitat context [@mcgregor2015feral]. In some cases, a small number of cats can inflict large damage to local fauna populations [@tuft2021cats; @greenwell2019cat; @moseby2019understanding].  

There is concern that large macropods (kangaroos and wallabies) may become overabundant following fox control (as foxes are their primary terrestrial predators where dingoes are absent), thereby increasing their grazing pressure [@doherty2017stop]. In turn, this could reduce the understorey habitat structure required by smaller prey species for shelter, and consequently increase prey exposure to invasive predators. There is some evidence to support this [@banks2000predation; @dexter2013unintended]. @geary2020predators found no effect of fox control on herbivore occurrence in the Glenelg region, but herbivore release in terms of density, recruitment rates and behaviour are worth further investigation. 

Changes in cat diel activity patterns following fox control could cause cats to switch prey species. Cats are mostly nocturnal, partly because they are likely tracking the activity of small mammals, their preferred prey species [@doherty2015continental]. I found that cats in dry vegetation types shifted to predominantly diurnal behaviour where fox activity was high (Fig. \@ref(fig:diel-cat-fox)). I expect this to shift impacts from small mammals to mostly reptiles and birds which are active during the day. However, in wet forests, cats reduced activity at dawn in response to high fox activity (Fig. \@ref(fig:diel-cat-fox)), limiting the total amount of time spent hunting. Further, cats were less detectable in their activity centres in wet forests, potentially reflecting a more cautious hunting strategy (Chapter \@ref(density)). It is therefore plausible that fox suppression may increase the impact of cats on native prey, although perhaps onto different species. Given our current lack of ability to generalise behaviour changes and understanding about how different predator behaviours impact prey, this is a strong priority for future research [@wirsing2021context].

These factors make it difficult to predict what impact mesopredator release of feral cats will have on native prey of concern. Even with mesopredator release of feral cats, fox control has value as a conservation action [@hunter2018not]. However, fox control programs are rarely monitored in ways which can reliably detect which species are responding positively, neutrally or negatively to fox control [@reddiex2007control; @reddiex2006control]. I hope my thesis does not discourage the use of targeted fox control but encourages the careful monitoring of feral cats and a wider range of shared prey taxa (particularly species that might be highly vulnerable to cats). If cat density increases considerably, or particular native species show signs of decline, lethal cat control should be integrated with fox control [e.g., @comer2020integrating]. We must recognise, however, that integrated predator control can be challenging, particularly in temperate environments where broadscale cat control is largely infeasible [@lazenby2015effects; @fisher2015cat]. Indirect predator management, such as invasive prey [@mcgregor2020short] or large herbivore [@stobo2020habitat] management, or more targeted prey species-specific conservation actions could also be employed. In dire situations, fox control could be ceased, however this would lose the earlier value of fox control. The singular control of an invasive predator may take the pressure off some native species, but is unlikely to improve the persistence of all native prey species in systems where multiple invasive predators co-occur.
