# General Introduction 

State of the debate. How it impacts Australian ecosystem management. 
Background information on the ecology of case study predators in Australia. 

## Mesopredator release hypothesis 

"In the absence of large predators, smaller predators can become more abundant (mesopredator release) and, in turn, may cause the local extinction of vulnerable prey species." - @soule1988reconstructed. 

Against a backdrop of growing evidence that top predators can apply top-down pressure on subordinate predator species (in addition to prey), @soule1988reconstructed first coined 'mesopredator release'. Grounded in basic food web theory, the mesopredator release hypothesis (hereafter 'MRH') is a simple and intuitive ecological theory. So why, 33 years later, is mesopredator release one of the most contentious hypotheses in applied ecology? 

Firstly, there is a lack of replicated, robust evidence for the MRH. This is partly because predators are difficult to monitor, particularly using experimental designs. The average mammalian predator is cryptic and occurs widely across broad habitats, at low densities. To obtain sufficient sample sizes for statistical models, a very large area needs to be surveyed intensively for predators [@royle2008statistical]. Even still, limited inference can be gleaned from occupancy models when nearly everywhere is suitable habitat and site occurrence probability is close to one if you monitor for long enough [@efford2012occupancy]. Due to the large area predator populations occur over, there often aren't comparable landscapes without declines to compare against, or at least ones which are spatially independent. Without robust experimental designs, it is difficult to attribute changes in mesopredator populations to apex predator declines. 

Secondly, critics argue that the MRH is an overly simplistic representation of complex ecosystems. Most evidence for mesopredator release comes from North America and other regions with many co-occurring large carnivores [@ritchie2009predator]. MRH refers to a singular, direct negative association between a dominant predator and a subordinate species, overlooking the web of positive, negative, direct, indirect and probably nonlinear [@johnson2007rarity] interactions which occur in multipredator systems [@levi2012wolves; @prugh2020enemies; @finke2004predator]. Additionally, bottom-up processes (i.e., ecosystem productivity and prey availability) interact with top-down processes to determine the strength of mesopredator release [@elmhagen2007trophic]. Intensive multispecies monitoring and complex statistical methods are therefore required to disentangle mesopredator release from the background drivers of predator populations, but this has rarely taken place. As a result, we lack key detail on the conditions which drive the occurrence and strength of mesopredator release.

Thirdly, mesopredator release remains a blurry concept because of a reliance on vague population metrics. How exactly mesopredators are expected to respond to apex predator declines and what threshold defines "release" is not clearly stipulated [@jachowski2020identifying]. Many of the MRH field studies reviewed by @jachowski2020identifying provided mixed support because different population metrics provided conflicting inference. @jachowski2020identifying called for clearer separation of spatial, numerical and behavioural processes, which are wrapped together in commonly used "abundance" and "activity" indices [@stephens2015management]. These traditional survey and statistical methods also have an ill-defined spatial and temporal resolution; this is problematic because sampling scale impacts the direction of perceived species interactions [@guillaume2020co-occurrence; @efford2012occupancy].  

Uncertainty around the MRH hinders effective conservation management. The functioning of global ecosystems has been degraded by widespread declines in large carnivores [@ripple2014status]. Managers therefore need to predict outcomes of continued declines, improvements and reintroductions of carnivore populations. Invasive predators are also a leading causes of global biodiversity and economic declines [@bellard2016global; @doherty2016invasive] and their control--usually lethal--is a prevalent management strategy (**ref**). However, when multiple invasive species occur, single invasive species control often has perverse outcomes on native species, likely due to 'release' effects [@ballari2016potential]. Invasive predators likely have greater impact on native prey relative to native predators because prey are naive to the threat invasive predators pose and lacked time to evolve antipredator behaviours [@sih2010predator; @salo2007alien]. A better understanding of the interactions between invasive predators is key to improving conservation outcomes [@zavaleta2001viewing; @doherty2017stop]. 

Debate over the MRH rages in Australia--a continent which has 'institutionalised' poisoning predators [@philip2019institutionalisation]. The dingo *Canis familiaris* is Australia's native mammalian apex predator and is widely persecuted, mainly for its agricultural impacts [@smith2015dingo]. Reduced distribution and density is expected to have caused a mesopredator release of the introduced red fox *Vulpes vulpes* (hereafter 'fox') and feral cat *Felis catus* (hereafter 'cat'), in turn contributing to Australia ongoing extinction crisis [@johnson2007rarity; @newsome2017top; @woinarski2015ongoing; @woinarski2019reading]. Mammals in the 35 - 5500 g weight range are the preferred meal size for these invasive mesopredators and have declined most strongly since the European colonisation of Australia [@murphy2014critical; @burbidge1989patterns]. However, evidence for invasive mesopredator release is contentious to say the least [@allen2011wild; @allen2013clear; @hayward2015ecologists; @doherty2017stop; @hunter2018not; @nimmo2015dingoes; @fleming2012seven]. 

The MRH considers a predator guild comprising of two species, but what happens following apex predator decline when there are multiple subordinate species? Literature around the dingo-debate hypothesises both foxes and cats to benefit from dingo decline. Alternative theory predicts an among-carnivore cascade [@levi2012wolves]: in a dingo (~15 kg) - fox (~6 kg) - cat (~4 kg) hierarchy, dingo suppression would benefit foxes, which would in-turn disadvantage cats. Competition between these introduced predators should be high; foxes and cats have high dietary overlap [@stobo2021reptiles; @stobo2021sharing] and occupy a similar niche [@glen2005complex]. Although, evidence that foxes exert top-down pressure on cats is unclear. 

Strongest evidence of fox-cat interactions comes from targeted lethal fox control programs in southern parts of Australia where the medium-large carnivore guild comprises entirely of these two predators. Foxes are managed primarily for biodiversity conservation in protected areas, although few programs have demonstrated improvements and several long-term studies have reported perverse outcomes [@wayne2017recoveries; @lindenmayer2018conservation; @duncan2020eruptive; @dexter2009impact; @kinnear2016fox]. A mesopredator release of cats is commonly suspected to be the cause [@doherty2017stop; @wayne2017recoveries; @marlow2015cats], although, @duncan2020eruptive offers an alternative hypothesis regarding prey overshooting carrying capacities. Strong evidence comes from the @risbey2000impacts experiment: capture-rates of shared mammalian prey worsened with targeted fox control, but increased when both foxes and cats were suppressed. Indeed, cat activity appears to increase on average following targeted fox control, but there is considerable uncertainty around this estimate [@hunter2018not]. Interestingly, @molsher2017mesopredator observed no change in the 'abundance' of cats, but identified changes in diet and space use following fox control. No study has directly estimated feral cat density in response to fox control. Distinguishing numerical population change from behavioural changes is a clear priority to improve understanding of fox-cat interactions and mesopredator release in Australia. 


###	European red foxes in Australia 
Europeans introduced foxes from Great Britain into Australia (at least eight times) in the early 1870's for the purpose of sport hunting [@fairfax2019dispersal]. Once established in southern Victoria, foxes spread quickly across temperate and sub-tropical mainland Australia [@fairfax2019dispersal]. Today, foxes are ubiquitous expect in tropical areas of Northern Australia (and many offshore islands).  

Foxes live in family groups comprising a dominant pair and their juvenile cubs. If resource availability is high, subordinate adult offspring may also remain with the group. Fox density in Australia varies from less than 0.1 foxes per km^2^ in semi-arid regions to more than four foxes per km^2^ in productive environments such as farmlands and wetlands. Fox home range size follows the opposite pattern, varying from less than 100 ha in urban and productive agricultural environments, to upwards of 2000 ha in the arid zone. Foxes within the family group share a home range, but usually hunt alone. Fox home ranges are dynamic: they can drift through time, involve excursions to concentrated food resources, and change rapidly if resource availability alters or a neighbouring home range becomes vacant (it only takes 8 days - 1 month for a vacant home range to be taken over).

Foxes have a strongly seasonal lifecycle: mating occurs in mid-winter, cubs are born in spring, and offspring disperse in autumn and early winter, before breeding that season. Survival and fecundity rates vary with age and local conditions, and litter size may increase after lethal control. Sex ratios at birth usually approximate parity. The proportion of young that disperse also varies, but males are more likely to disperse than females, and disperse further on average.

Foxes typically consuming about 380 grams of food per day (ref). True generalists, they feed on a wide variety of live prey, from livestock to small arthropods, as well as carrion and fruits. 

 
###	Feral cats in Australia

As a consequence of human introductions, domestic cats Felis catus have a near-global distribution, occurring on all continents except Antarctica and on hundreds of islands (Long 2003). Cats are successful invaders because they have versatile diets (Bonnaud et al. 2011) and habitat use (Doherty et al. 2014), high fecundity and wide thermal tolerance, and do not require free drinking water (Bradshaw et al. 2013). Domestic cats were introduced to Australia in 1788. They spread rapidly and are now found as feral populations across the entire mainland and many of the larger offshore islands. 

Domestic cats become feral (hereafter ‘feral cats’) when they live independently of humans in the wild; they are termed stray cats when they depend on humans for incidental provision of food or shelter (Denny & Dickman 2010). 

Cat social organisation and behaviour is highly variable. In areas with rich resources, such as rubbish tips, farms and seabird colonies, cats live in dense matrilineal societies, and dozens of cats may share a small area.  Across Australia’s more typical natural environments, however, cats are largely solitary. In these environments, densities vary from 0.01 to 7 cats per km2, depending on prey availability.

Female cat home range size is likewise variable, scaling from less than 100 ha to more than 600 ha (reviewed in Hamer et al. in press), but shows the opposite relationship with productivity. Female cats have small, partially-overlapping home ranges when annual productivity is high, and large home ranges when productivity is low, provided that seasonal variation is also low; where seasonality is high, this relationship is less clear (Bengsen et al. 2016). 

The home range size of male cats varies with that of females, but is larger on average because dominant males typically overlap the ranges of two to three females. Both sexes may also have ranges that partially overlap ranges of other cats of the same sex. Cats can travel far beyond their home range, particularly in response to rapid changes in resource availability (e.g. because of fire or rabbit control), and some individuals do not have a fixed home range.

Female cats attain sexual maturity from as early as 5 months, but usually at 8 - 12 months, typically once they are at least 2.5 kg in weight. Females have one to three litters of ~4 kittens each a year. The winter non-breeding period is longer in cool climates than warm ones, and so the breeding season varies from four to nine months accordingly.  Dispersal behaviour is not well documented, but male cats are likely to disperse more often and further than females.
Feral cat survival rates are poorly studied, especially in natural habitats.  Kitten mortality rates are likely to be high, and most cats probably live no more than three to five years.

Cats eat approximately 200 g of prey a day. They use ‘sit and wait’ and stalking strategies to catch a wide variety of vertebrates and insects, and will also occasionally scavenge on dead animals. Individual cats may specialise on prey groups, such as birds or small mammals.

Feral cats are implicated in 26% of bird, mammal and reptile species extinctions worldwide (Doherty et al. 2016). They affect native species mostly through predation (Medina et al. 2011), but also through competition (Medina et al. 2014), disease transmission (Dubey 2008), and hybridisation (i.e. with the wildcat Felis silvestris; Beaumont et al. 2001). Feral cats also have socio-economic impacts, mostly as disease vectors affecting agricultural production and human health (Dubey 2008).
 
Cat populations are difficult to control because cats do not readily take most types of meat bait (Algar et al. 2002), but cats have been eradicated from relatively small areas using a combination of exclusion fencing, shooting, trapping, and poisoning (Moseby et al. 2009).
Garrard 2020. 


## Lethal fox control
Done globally. 
As foxes can be relatively easily culled6 (unlike feral cats7), more land is managed and resources spent on their management than any other invasive vertebrate in Australia
Predominant conservation action in Australia. 


Poison baiting with 1080 (sodium fluoroacetate) is the primary fox management approach in Australia (Saunders, Gentle, & Dickman, 2010). 

Threat management for vertebrate species usually involves lethal control of invasive predators—a major cause of global declines (Burbidge et al. 2012; Doherty et al. 2016). Despite this, declines regularly continue (Ballari et al. 2016; Wayne et al. 2017b). This is primarily attributed to an insufficient reduction in the density of the controlled invasive predator (e.g. Lieury et al. 2015), or a “release” of subordinate species (e.g. Ruscoe et al. 2011). A prominent example is Australia’s widespread use of 1080 poison baits to kill canid predators, which may potentially heighten the impacts of feral cats, Felis catus, and overgrazing by various herbivores on threatened, native mammals (Doherty & Ritchie 2017). However, difficulties in monitoring and modelling these complex multispecies interactions has led to contention (Hayward & Marlow 2014).

Native mammal responses to fox suppression in Australia have been highly variable. Though, a temporal trend in the response of critical weight-range mammals is often observed: where populations spike in the short-term (1 - 3 years post-control)11,12, taper off closer to pre- control levels in the medium-term (5 - 15 years post-control)13–15 and decline to pre-control levels or worse (including local extinctions) in the long-term (15+ years post-control)16–20. This could be explained by:
(i) reduced top-down control leading to the population overshooting, then stabilising at the carrying capacity of the environment21.
(ii) A mesopredator release of feral cats (particularly in regions where dingoes are absent)22 due to apex predator suppression and/or increased prey availability.
(iii) A release of larger herbivores (macropods and possums) due to fox suppression (increasing competition and altering habitat structure)13,22,23.
(iv) compensatory responses of foxes to control (e.g. increasing reproduction rates)24, and/or learned bait aversion25,26.
However, most fox control programs have not been surveyed in a way that can test these explanations, nor disentangle natural variation and the impact of other threats (e.g. drought).


Effort / lack of fox suppression
Baiting at large scales (>500 km2) and high densities (5+ baits per km2) can greatly reduce fox densities, with populations remain- ing low for several months (Berry et al., 2014; Thomson et al., 2000). In contrast, patchy or smaller-scale control may result in little detect- able change in fox density (Bengsen, 2014; Newsome, Crowther, & Dickman, 2014), or even increase fox activity or abundance through compensatory immigration (Lieury et al., 2015; Towerton, Dickman, Kavanagh, & Penman, 2016). Considerable uncertainty remains about the efficacy of low-intensity landscape-scale fox manage- ment for biodiversity conservation (Robley, Gormley, Forsyth, & Triggs, 2014; Towerton et al., 2016; Walsh, Wilson, Benshemesh, & Possingham, 2012), and the design of more effective management is hampered by a lack of tools for predicting the effects of control.






